import "./globals.css";

export const metadata = {
  title: "Yves NEXT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        {children}
        <hr />
        <p className=" text-center text-slate-600 pt-10 pb-10">Text in the Root layout</p>
        <hr />
      </body>
    </html>
  );
}
